# set
## 1. set의 정의

set은 중복이 없는 요소들로 구성된 컬렉션입니다. 여러분이 배운 집합을 떠올려 보면 간단합니다. 중복이라는 것이 존재하지 않으며, 중복된 요소가 입력되는 경우
무시하게 됩니다. 또한 set은 순서가 없는 것이 특징입니다. 들어온 순서 혹은 정렬이 없다는 뜻입니다. 
이를 이용하면 다음과 같은 조작을 할 수 있습니다. 리스트나 튜플에 중복이 없는 값들을 받고 싶을 때 형변환하여 사용할 수 있습니다. 
set은 다음과 같은 기호를 사용합니다. 

__{ }__

In [ ]:
### set의 선언

my_set = {} #이와 같은 선언은 dictionary 가 됩니다. 

my_set = {1,2,3,4,5,1,1,2,2,3,3}
print( my_set ) #결과 {1, 2, 3, 4, 5}

my_list = ['a','b','c','a','a','c','f']
my_set = set(my_list)
print( my_set ) #결과 {'a', 'b', 'c', 'f'}
my_set={1,2,3,4,5}
1 in my_set #결과 True
10 in my_set #결과 False

2. set의 추가 삭제 

set에서는 추가 삭제를 메소드를 통해서 할 수 있습니다. 따라서 기본 메소드와 함께 알아봅시다.

In [ ]:
my_set = set()
print( my_set ) #결과 {}
my_set.add(1) 
print( my_set ) #결과 {1}
my_set.update({1,2,3,4,5})
print( my_set ) #결과 {1,2,3,4,5}

In [ ]:
my_set={1,2,3,4,5}
my_set.remove(1)
print( my_set ) #결과 {2,3,4,5}
# my_set.remove(1) #에러 발생
my_set.discard(2)
my_set.discard(2)
print( my_set ) #결과 {3,4,5}

print( my_set.pop() ) #결과 랜덤...

## 2. set의 연산
set은 집합과 같기 때문에 연산이 가능합니다. 이때 주의해야 할 것은 집합의 기준으로 생각해야 한다는 것입니다.
기본적으로 합집합, 교집합, 차집합 과같은 연산이 지원 됩니다.

In [ ]:
### set의 합집합
set_1 = {1,2,3}
set_2 = {3,4,5}

set_3 = set_1 | set_2
print( set_3 ) #결과 {1,2,3,4,5}
set_3 = set_1.union(set_2)
print( set_3 ) #결과 {1,2,3,4,5}

In [ ]:
### set의 교집합
set_1 = {1,2,3}
set_2 = {3,4,5}

set_3 = set_1 & set_2
print( set_3 ) #결과 {3}
set_3 = set_1.intersection(set_2)
print( set_3 ) #결과 {3}

In [ ]:
### set의 차집합
set_1 = {1,2,3}
set_2 = {3,4,5}

set_3 = set_1 - set_2
print( set_3 ) #결과 {1,2}
set_3 = set_1.difference(set_2)
print( set_3 ) #결과 {1,2}

In [ ]:
set_1 = {1,2,3}
set_2 = {3,4,5}
set_1.intersection_update(set_2)
print(set_1)

# loop

## 1. for문
for를 사용하는 루프는 파이썬에서 반복을 위해 사용됩니다. 
파이썬은 조금 특이하게 연속된 자료의 형태(리스트, 문자열, 튜플,사전 등)와 같이 반복이 가능한 자료형태들에 대해 동작합니다.
파이썬의 for 루프는 다음과 같은 형태를 갖습니다.

```python3
for item in object:
    statements
```

이때 아이템의 이름을 여러분이 알기 쉬운 것으로 정하는 것이 좋습니다. 나중에 코드를 다시 읽었을 때, 그 내용을 파악하기 쉽게 하기 위함입니다.

In [ ]:
## 리스트의 반복

my_list = [1, 2, 3, 4, 5]

for element in my_list:
    print(element)

In [ ]:
## 리스트의 반복을 이용한 짝수 추출
my_list = [1, 2, 3, 4, 5]
for num in my_list:
    if num % 2 == 0:
        print('{} 짝수입니다'.format(num))
    else:
        print('{} 홀수입니다.'.format(num))

In [ ]:
## 리스트의 반복을 이용한 합의 계산
my_list = [1, 2, 3, 4, 5]
list_sum = 0
for num in my_list:
    list_sum = list_sum + num
print(list_sum)

In [ ]:
## 문자열의 반복

my_string = 'Hello World!, this is python!'

for letter in my_string:
    print(letter)

In [ ]:
## 튜플의 반복
my_tuple = (1, 2, 3, 4, 5)
for item in my_tuple:
    print(item)

In [ ]:
my_list = [(2, 4), (6, 8), (10, 12)]

for tup in my_list:
    print(tup)

for first, second in my_list:
    print('first is {} , second is {}'.format(first,second))

for tup in my_list:
    for item in tup:
        print(item,end=' ')
    print()

In [ ]:
## 딕셔너리의 반복

my_dict = dict(k1=40, k2=50, k3=60)

for key,v in my_dict.items():
    print(key, v,type(key))
for key in my_dict.keys():
    print(key)
for value in my_dict.values():
    print(value)

2. for문을 위한 도구 range
range는 하나의 함수입니다. range는 자동으로 숫자로 이루어진 리스트를 반환합니다.(python2기준) . 형식이 조금 특이한데 다음과 같은 형식입니다.
```python3
range( stop )
range( start, stop[, step])
```

처음 형식은 조금 낮설수 있으나, 두번째 형식은 우리가 연속된 자료형태에서 슬라이싱과 비슷합니다. 이를 사용하여 for문을 좀 더 
효과적으로 사용해 봅시다.

In [ ]:
range(1,10)

In [ ]:
for i in range(1,10):
    print(i)

## while문
while문은 조건이 참인경우 반복하여 실행하는 구문이다. 구조는 다음과 같다

```python3
while 조건:
    수행할명령
```

while문에서 주의해야 할 점은 무한 루프에 빠질 수 있다는 것이다. 무한 루프에 빠지지 않게 항상 탈출할 조건을 주어야 한다.

In [1]:
a = 1
while True:
    a+=1
    if a % 2 ==0:
        if a <500: continue
        print('{}는 짝수 입니다.'.format(a))
    if a>1000:
        break

500는 짝수 입니다.
502는 짝수 입니다.
504는 짝수 입니다.
506는 짝수 입니다.
508는 짝수 입니다.
510는 짝수 입니다.
512는 짝수 입니다.
514는 짝수 입니다.
516는 짝수 입니다.
518는 짝수 입니다.
520는 짝수 입니다.
522는 짝수 입니다.
524는 짝수 입니다.
526는 짝수 입니다.
528는 짝수 입니다.
530는 짝수 입니다.
532는 짝수 입니다.
534는 짝수 입니다.
536는 짝수 입니다.
538는 짝수 입니다.
540는 짝수 입니다.
542는 짝수 입니다.
544는 짝수 입니다.
546는 짝수 입니다.
548는 짝수 입니다.
550는 짝수 입니다.
552는 짝수 입니다.
554는 짝수 입니다.
556는 짝수 입니다.
558는 짝수 입니다.
560는 짝수 입니다.
562는 짝수 입니다.
564는 짝수 입니다.
566는 짝수 입니다.
568는 짝수 입니다.
570는 짝수 입니다.
572는 짝수 입니다.
574는 짝수 입니다.
576는 짝수 입니다.
578는 짝수 입니다.
580는 짝수 입니다.
582는 짝수 입니다.
584는 짝수 입니다.
586는 짝수 입니다.
588는 짝수 입니다.
590는 짝수 입니다.
592는 짝수 입니다.
594는 짝수 입니다.
596는 짝수 입니다.
598는 짝수 입니다.
600는 짝수 입니다.
602는 짝수 입니다.
604는 짝수 입니다.
606는 짝수 입니다.
608는 짝수 입니다.
610는 짝수 입니다.
612는 짝수 입니다.
614는 짝수 입니다.
616는 짝수 입니다.
618는 짝수 입니다.
620는 짝수 입니다.
622는 짝수 입니다.
624는 짝수 입니다.
626는 짝수 입니다.
628는 짝수 입니다.
630는 짝수 입니다.
632는 짝수 입니다.
634는 짝수 입니다.
636는 짝수 입니다.
638는 짝수 입니다.
640는 짝수 입니다.
642는 짝수 입니다.
644는 짝수 입니다.
646는 짝수 입니다.
648는 짝수 입니다.
650는 짝수 입니다.
652는 짝수 입니다.
654는 짝수 입니다.
656는 짝수 입니다.
658는 짝수 입니다.
660는 짝수 입니다.
662는 짝수 입니다.
664는 짝수 입니다.
666는 짝수 입니다.
668는 짝수 입니다.
670는 짝수 입니다.
672는 짝수 입니다.
674는 짝수 입니다.
676는 짝수 입니다.
678는 짝수 입니다.
680는 짝수 입니다.
682는 짝수 입니다.
684는 짝수 입니다.
686는 짝수 입니다.
688는 짝수 입니다.
690는 짝수 입니다.
692는 짝수 입니다.
694는 짝수 입니다.
696는 짝수 입니다.
698는 짝수 입니다.
700는 짝수 입니다.
702는 짝수 입니다.
704는 짝수 입니다.
706는 짝수 입니다.
708는 짝수 입니다.
710는 짝수 입니다.
712는 짝수 입니다.
714는 짝수 입니다.
716는 짝수 입니다.
718는 짝수 입니다.
720는 짝수 입니다.
722는 짝수 입니다.
724는 짝수 입니다.
726는 짝수 입니다.
728는 짝수 입니다.
730는 짝수 입니다.
732는 짝수 입니다.
734는 짝수 입니다.
736는 짝수 입니다.
738는 짝수 입니다.
740는 짝수 입니다.
742는 짝수 입니다.
744는 짝수 입니다.
746는 짝수 입니다.
748는 짝수 입니다.
750는 짝수 입니다.
752는 짝수 입니다.
754는 짝수 입니다.
756는 짝수 입니다.
758는 짝수 입니다.
760는 짝수 입니다.
762는 짝수 입니다.
764는 짝수 입니다.
766는 짝수 입니다.
768는 짝수 입니다.
770는 짝수 입니다.
772는 짝수 입니다.
774는 짝수 입니다.
776는 짝수 입니다.
778는 짝수 입니다.
780는 짝수 입니다.
782는 짝수 입니다.
784는 짝수 입니다.
786는 짝수 입니다.
788는 짝수 입니다.
790는 짝수 입니다.
792는 짝수 입니다.
794는 짝수 입니다.
796는 짝수 입니다.
798는 짝수 입니다.
800는 짝수 입니다.
802는 짝수 입니다.
804는 짝수 입니다.
806는 짝수 입니다.
808는 짝수 입니다.
810는 짝수 입니다.
812는 짝수 입니다.
814는 짝수 입니다.
816는 짝수 입니다.
818는 짝수 입니다.
820는 짝수 입니다.
822는 짝수 입니다.
824는 짝수 입니다.
826는 짝수 입니다.
828는 짝수 입니다.
830는 짝수 입니다.
832는 짝수 입니다.
834는 짝수 입니다.
836는 짝수 입니다.
838는 짝수 입니다.
840는 짝수 입니다.
842는 짝수 입니다.
844는 짝수 입니다.
846는 짝수 입니다.
848는 짝수 입니다.
850는 짝수 입니다.
852는 짝수 입니다.
854는 짝수 입니다.
856는 짝수 입니다.
858는 짝수 입니다.
860는 짝수 입니다.
862는 짝수 입니다.
864는 짝수 입니다.
866는 짝수 입니다.
868는 짝수 입니다.
870는 짝수 입니다.
872는 짝수 입니다.
874는 짝수 입니다.
876는 짝수 입니다.
878는 짝수 입니다.
880는 짝수 입니다.
882는 짝수 입니다.
884는 짝수 입니다.
886는 짝수 입니다.
888는 짝수 입니다.
890는 짝수 입니다.
892는 짝수 입니다.
894는 짝수 입니다.
896는 짝수 입니다.
898는 짝수 입니다.
900는 짝수 입니다.
902는 짝수 입니다.
904는 짝수 입니다.
906는 짝수 입니다.
908는 짝수 입니다.
910는 짝수 입니다.
912는 짝수 입니다.
914는 짝수 입니다.
916는 짝수 입니다.
918는 짝수 입니다.
920는 짝수 입니다.
922는 짝수 입니다.
924는 짝수 입니다.
926는 짝수 입니다.
928는 짝수 입니다.
930는 짝수 입니다.
932는 짝수 입니다.
934는 짝수 입니다.
936는 짝수 입니다.
938는 짝수 입니다.
940는 짝수 입니다.
942는 짝수 입니다.
944는 짝수 입니다.
946는 짝수 입니다.
948는 짝수 입니다.
950는 짝수 입니다.
952는 짝수 입니다.
954는 짝수 입니다.
956는 짝수 입니다.
958는 짝수 입니다.
960는 짝수 입니다.
962는 짝수 입니다.
964는 짝수 입니다.
966는 짝수 입니다.
968는 짝수 입니다.
970는 짝수 입니다.
972는 짝수 입니다.
974는 짝수 입니다.
976는 짝수 입니다.
978는 짝수 입니다.
980는 짝수 입니다.
982는 짝수 입니다.
984는 짝수 입니다.
986는 짝수 입니다.
988는 짝수 입니다.
990는 짝수 입니다.
992는 짝수 입니다.
994는 짝수 입니다.
996는 짝수 입니다.
998는 짝수 입니다.
1000는 짝수 입니다.